# Generated by Django 3.2.18 on 2023-05-13 13:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_auto_20230513_1331'),
        ('musics', '0002_musiccomponent'),
        ('accounts', '0007_alter_user_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='music_components',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='musics.musiccomponent'),
        ),
        migrations.AddField(
            model_name='user',
            name='playlist',
            field=models.ManyToManyField(blank=True, to='musics.Music'),
        ),
        migrations.CreateModel(
            name='MusicUserLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('music', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='musics.music')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.user')),
            ],
        ),
        migrations.CreateModel(
            name='MovieUserLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies.movie')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.user')),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='like_movie',
            field=models.ManyToManyField(blank=True, related_name='users_like_movies', through='accounts.MovieUserLike', to='movies.Movie'),
        ),
        migrations.AddField(
            model_name='user',
            name='like_music',
            field=models.ManyToManyField(blank=True, related_name='users_like_musics', through='accounts.MusicUserLike', to='musics.Music'),
        ),
    ]
