# Generated by Django 3.2.18 on 2023-05-18 03:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20230513_1331'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='like_movie',
        ),
    ]
