# Generated by Django 3.2.18 on 2023-05-20 06:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_remove_user_is_active'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MovieUserLike',
        ),
    ]
