# Generated by Django 3.2.18 on 2023-05-13 12:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_user_profile_picture'),
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='original_title',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.CreateModel(
            name='MusicUserLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies.movie')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.user')),
            ],
        ),
        migrations.AddField(
            model_name='movie',
            name='like_movie',
            field=models.ManyToManyField(related_name='users_like_movies', through='movies.MusicUserLike', to='accounts.User'),
        ),
    ]
