# Generated by Django 3.2.18 on 2023-05-13 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musics', '0002_musiccomponent'),
        ('movies', '0002_auto_20230513_1200'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='like_movie',
        ),
        migrations.AddField(
            model_name='movie',
            name='ost',
            field=models.ManyToManyField(related_name='movie_ost', to='musics.Music'),
        ),
        migrations.DeleteModel(
            name='MusicUserLike',
        ),
    ]
