# Generated by Django 3.2.18 on 2023-05-16 06:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('musics', '0002_musiccomponent'),
    ]

    operations = [
        migrations.RenameField(
            model_name='music',
            old_name='tiitle',
            new_name='title',
        ),
    ]
