# Generated by Django 3.2.18 on 2023-05-16 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musics', '0003_rename_tiitle_music_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='music',
            name='youtube_uri',
            field=models.URLField(null=True),
        ),
    ]
