# Generated by Django 3.2.18 on 2023-05-16 08:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('musics', '0004_music_youtube_uri'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='music',
            name='youtube_uri',
        ),
    ]
