# Generated by Django 3.2.18 on 2023-05-17 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musics', '0005_remove_music_youtube_uri'),
    ]

    operations = [
        migrations.AddField(
            model_name='musiccomponent',
            name='vector',
            field=models.FloatField(null=True),
        ),
    ]
