# Generated by Django 3.2.18 on 2023-05-18 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musics', '0007_alter_musiccomponent_vector'),
    ]

    operations = [
        migrations.AddField(
            model_name='music',
            name='album_cover',
            field=models.URLField(blank=True),
        ),
    ]
