# Generated by Django 3.2.18 on 2023-05-18 01:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('musics', '0008_music_album_cover'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='musiccomponent',
            name='vector',
        ),
    ]
