# Generated by Django 3.2.18 on 2023-05-23 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musics', '0009_remove_musiccomponent_vector'),
    ]

    operations = [
        migrations.AddField(
            model_name='music',
            name='youtube_url',
            field=models.TextField(blank=True),
        ),
    ]
