# Generated by Django 3.2.18 on 2023-05-23 08:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('musics', '0010_music_youtube_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='music',
            old_name='youtube_url',
            new_name='video_id',
        ),
    ]
