# Generated by Django 3.2.18 on 2023-05-24 00:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('musics', '0011_rename_youtube_url_music_video_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='music',
            name='video_id',
        ),
    ]
